name: Build and Push Docker Image

# Când se rulează workflow-ul
on:
  push:
    branches: [ master ]  # La fiecare push pe branch-ul main
  pull_request:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout codul
    - name: Checkout code
      uses: actions/checkout@v4
    
    # 2. Login în DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # 3. Extrage versiunea din app.py
    - name: Extract version from app.py
      id: get_version
      run: |
        VERSION=$(grep -oP '"version"\s*:\s*"\K[^"]+' app.py)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Extracted version: $VERSION"
    
    # 4. Build și push imaginea cu versiunea din app.py
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          mariuseu/my-flask-app:${{ steps.get_version.outputs.version }}
          mariuseu/my-flask-app:latest
